### ISSUE TITLE
Mk

### ISSUE THREAD

**Issue by Marcosmk12** [readyio/RGN-SDK-Example#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KonstantinGetready** [comment]
Hello @Marcosmk12, do you have some questions/problems with the SDK integration?

**Comment by Marcosmk12** [comment]
name: Java Main Workflow

on:
  pull_request:
    branches: [ master, rc-** ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        java-version: [ 8, 11, 17 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Run checkstyle
        run: mvn checkstyle:check
      - name: Run unit tests
        run: mvn clean test
      - name: Build with Maven
        run: mvn install '-Dgpg.skip=true' '-Dmaven.javadoc.skip=true'
